services:

  postgres:
    image: postgres:17

    container_name: vellum_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vellum_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: vellum_backend

    env_file:
      - ./backend/.env.docker

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend

    container_name: vellum_frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    environment:
      VITE_API_URL: http://localhost:8000

    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: